### ISSUE TITLE
xiFDR parameters

### ISSUE THREAD

**Issue by SimpleNumber** [Rappsilber-Laboratory/xiFDR#31]
Hi there!

I am trying to use xiSearch and xiFDR in the command line (Linux system) but have some questions about xiFDR parameters:

1. What are the default values for all FDRs that you have? I can launch xiFDR actually with no FDR specification, so apparently, it uses smth.
2. Which FDR is better to use in practice? Because you have so many of them (even ranges) I am a bit lost.
3. In which format FDR has to be written? (0.01 or 1 meaning 1% FDR)
4. Is there a way to start xiSearch and xiFDR one after another how it is done in GUI? or, at least, is there a way to export all FDR settings used in GUI?
5. Can you please give a more detailed explanation of "fileowner" parameter? When I run the xiFDR without this parameter I have an error that it is not specified, but I don't understand what exactly is missing, even though all FDR files are calculated.

Command I used:
```
java -Xmx30G -jar /path/to/xiFDR-2.1.5.5.jar /path/to/my/csv/result/file/from/xiSearch/results.csv --xiconfig=/path/to/xiSearch/config/file.conf --fasta=/path/to/fasta.fasta --csvOutDir=/path/to/output/dir/
```
for this I've got an error:
```
May 08, 2023 2:54:54 PM org.rappsilber.fdr.gui.components.MZIdentMLOwnerGUI getNewOwner
WARNING: NO OWNER PREDEFINED AND CAN'T ASK FOR ONE!
May 08, 2023 2:54:54 PM org.rappsilber.fdr.XiCSVinFDR main
SEVERE: null
java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at java.base/java.util.Properties.put(Properties.java:1316)
        at java.base/java.util.Properties.setProperty(Properties.java:225)
        at org.rappsilber.config.LocalProperties.setProperty(LocalProperties.java:79)
        at org.rappsilber.fdr.gui.components.MZIdentMLOwnerGUI.saveDefaultOwner(MZIdentMLOwnerGUI.java:78)
        at org.rappsilber.fdr.gui.components.MZIdentMLOwnerGUI.getSetOwner(MZIdentMLOwnerGUI.java:109)
        at org.rappsilber.fdr.XiCSVinFDR.main(XiCSVinFDR.java:458)
        at org.rappsilber.fdr.CommandLine.main(CommandLine.java:49)
```
And just before the error, I got the message:
```
...
INFO: Write linear peptide results to java.io.PrintWriter@29f69090
May 08, 2023 2:54:54 PM org.rappsilber.fdr.XiCSVinFDR$1 setComplete
INFO: Calculate Write Finished
May 08, 2023 2:54:54 PM org.rappsilber.fdr.XiCSVinFDR main
INFO: true true true
```

Thank you in advance!
Best,
Julia

**Comment by SimpleNumber** [comment]
Hi Filip,

Thank you! It's worked.

Best,
Julia

**Comment by grandrea** [comment]
re: option 4, xiSEARCH has a "Do FDR" setting that runs xiFDR and can be ticked in GUI
